import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Footer from "./components/Footer";
import "./glide.core.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "HTMACH",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex min-h-screen flex-col items-center justify-between">
          <Header />
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
