import "@/app/[locale]/globals.css";
import Footer from "@/components/layout/footer";
import NavBar from "@/components/layout/navbar";
import { FONT_PRETENDARD } from "@/lib/font-lib";
import { LanguageReturnType } from "@/lib/server/languages";
import { LocaleType } from "@/types/locale-type";
import { Metadata } from "next";

export type LocaleParmas = { locale: LocaleType };
export type MessageType = {
  translation: LanguageReturnType;
};

export async function generateStaticParams() {
  return [{ locale: "ko" }, { locale: "en" }];
}

export const metadata: Metadata = {
  title: "HTMACH",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: LocaleParmas;
}) {
  return (
    <html lang={locale}>
      <body className={FONT_PRETENDARD.className}>
        <main className="mt-20 flex flex-col items-center justify-between">
          <NavBar />
          {/* <Header locale={locale} /> */}
          {children}
          <Footer locale={locale} />
        </main>
      </body>
    </html>
  );
}
