import Footer from "@/components/Footer";
import Header from "@/components/Header";
import { cn } from "@/lib/utils";
import "@/styles/glide.core.min.css";
import "@/styles/globals.css";
import { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export async function generateStaticParams() {
  return [{ locale: "ko" }, { locale: "en" }];
}

export const metadata: Metadata = {
  title: "HTMACH",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: { locale },
}: {
  children: React.ReactNode;
  params: { locale: "en" | "ko" };
}) {
  return (
    <html lang={locale}>
      <body
        className={cn(
          "bg-background min-h-screen font-sans antialiased",
          fontSans.variable,
        )}
      >
        <main className="flex flex-col items-center justify-between">
          <Header locale={locale} />
          {children}
          <Footer locale={locale} />
        </main>
      </body>
    </html>
  );
}
